### ISSUE TITLE
Get data

### ISSUE THREAD

**Issue by OlivierBinette** [Duke-Chronicle-Project/article-extraction#8]
Get the newspaper scans from the library and make them available to the team.

**Comment by zbw8388** [comment]
Current status: I have randomly selected one issue from each year, and their data is in the `SelectedIssues` subfolder inside our onedrive database. Should we need a complete run through the archive, we can download each image when we need to process it given the large size of the entire archive.

**Comment by OlivierBinette** [comment]
Nice! Can you post the link to the onedrive here for reference?

**Comment by zbw8388** [comment]
https://prodduke-my.sharepoint.com/:f:/g/personal/nt94_duke_edu/EtKO5hai9JtIp-vi6g9iqkMBIbiAkgyRbD9dhGkvrMMflA?e=gtyYsQ
